"use client";

import { Download, Printer } from "lucide-react";
import { useRef } from "react";
import { ActionPill, Label } from "@/components/design-system";
import { CopyButton } from "@/components/copy-button";
import type { ProofReceipt } from "@/lib/receipt";
import { formatLocalTimestamp } from "@/lib/time";
import { getAllCitations } from "@/lib/citations";

export function HumanReadableReceipt({
  receipt,
}: {
  receipt: ProofReceipt;
}) {
  const printRef = useRef<HTMLDivElement>(null);
  const citations = getAllCitations(receipt);

  function handlePrint() {
    window.print();
  }

  return (
    <div className="space-y-8">
      {/* Print-friendly view */}
      <div
        ref={printRef}
        className="print-view space-y-8"
      >
        {/* Header */}
        <div className="border-b-2 border-border-default pb-6 print:border-black">
          <h2 className="text-2xl font-black sm:text-3xl">Proof of Existence</h2>
          <p className="mt-1 text-sm text-text-secondary">
            Generated by OpenProof &middot; {receipt.appVersion}
          </p>
        </div>

        {/* Summary */}
        <div className="grid gap-4 sm:grid-cols-2">
          <div>
            <Label color="muted">File</Label>
            <p className="mt-1 text-base font-semibold">{receipt.fileName}</p>
            <p className="text-xs text-text-muted">
              {receipt.fileMimeType} &middot; {(receipt.fileSize / 1024).toFixed(1)} KB
            </p>
            {receipt.proofType === "bundle" && receipt.bundleFiles ? (
              <p className="mt-1 text-xs text-text-muted">
                Bundle of {receipt.bundleFiles.length} files
              </p>
            ) : null}
          </div>
          <div>
            <Label color="muted">Status</Label>
            <p className="mt-1 text-base font-semibold text-accent">
              Registered on {receipt.chainName}
            </p>
            <p className="text-xs text-text-muted">
              {formatLocalTimestamp(receipt.createdTimestamp)}
            </p>
          </div>
        </div>

        {/* Fingerprint details */}
        <div>
          <Label color="muted">Cryptographic fingerprint</Label>
          <div className="mt-2 space-y-2">
            <DetailRow label="Algorithm" value={receipt.hashAlgorithm} mono />
            <DetailRow label="SHA-256" value={receipt.sha256Hash} mono />
          </div>
        </div>

        {/* Onchain details */}
        <div>
          <Label color="muted">Onchain registry</Label>
          <div className="mt-2 space-y-2">
            <DetailRow label="Blockchain" value={receipt.chainName} />
            <DetailRow label="Chain ID" value={String(receipt.chainId)} mono />
            <DetailRow label="Contract" value={receipt.contractAddress} mono />
            <DetailRow label="Transaction" value={receipt.transactionHash} mono />
            <DetailRow label="Registered by" value={receipt.creatorWallet} mono />
            {receipt.registryVersion ? (
              <DetailRow label="Registry version" value={`v${receipt.registryVersion}`} />
            ) : null}
          </div>
        </div>

        {/* Bundle files listing */}
        {receipt.proofType === "bundle" && receipt.bundleFiles ? (
          <div>
            <Label color="muted">Bundle file listing</Label>
            <div className="mt-2 divide-y divide-border-default text-sm">
              {receipt.bundleFiles.map((f, i) => (
                <div key={f.name} className="flex justify-between gap-4 py-2">
                  <span className="truncate">{i + 1}. {f.name}</span>
                  <span className="shrink-0 text-xs font-mono text-text-muted">{f.sha256.slice(2, 10)}</span>
                </div>
              ))}
            </div>
          </div>
        ) : null}

        {/* Verification URL */}
        <div>
          <Label color="muted">Verification</Label>
          <p className="mt-1 font-mono text-xs break-all">{receipt.verificationUrl}</p>
          {receipt.transactionUrl ? (
            <p className="mt-1 font-mono text-xs break-all text-text-muted">
              {receipt.transactionUrl}
            </p>
          ) : null}
        </div>
      </div>

      {/* Citations */}
      <div className="space-y-3">
        <Label color="muted">Citation formats</Label>
        {citations.map((c) => (
          <div key={c.label} className="rounded-xl bg-bg-surface-muted p-4 space-y-2">
            <div className="flex items-center justify-between">
              <p className="text-xs font-bold tracking-wider uppercase">{c.label}</p>
              <CopyButton label="Copy citation" value={c.citation} />
            </div>
            <pre className="whitespace-pre-wrap font-sans text-xs leading-relaxed text-text-secondary">
              {c.citation}
            </pre>
          </div>
        ))}
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-3 print:hidden">
        <ActionPill variant="secondary" onClick={handlePrint}>
          <Printer className="size-4" />
          Print / PDF
        </ActionPill>
      </div>

      {/* Print styles */}
      <style jsx global>{`
        @media print {
          body { background: white !important; color: black !important; }
          .print-view { padding: 0; max-width: 100%; }
          nav, footer, .print\\:hidden { display: none !important; }
          .border-b-2 { border-color: black !important; }
          .divide-y > * { border-color: #ccc !important; }
        }
      `}</style>
    </div>
  );
}

function DetailRow({
  label,
  value,
  mono,
}: {
  label: string;
  value: string;
  mono?: boolean;
}) {
  return (
    <div className="flex justify-between gap-4 py-1.5 border-b border-border-default text-sm">
      <span className="text-text-muted text-xs shrink-0">{label}</span>
      <span className={`text-right break-all ${mono ? "font-mono text-xs" : "text-sm"}`}>
        {value}
      </span>
    </div>
  );
}
